# Question -1
1. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.

In [5]:
import numpy as np
zeros = np.zeros(10, dtype = int)
ones = np.ones(10, dtype = int)
fives = np.full(10, 5, dtype=int)
result = np.concatenate((zeros,ones,fives))
print(result)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


# Question - 2
 Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [1]:
import numpy as np

# Generate values from 2 to 10 (inclusive) and reshape into a 3x3 matrix
values = np.arange(2, 11).reshape(3, 3)

print("3x3 Matrix with values from 2 to 10:")
print(values)

3x3 Matrix with values from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# Question - 3

In [2]:
import numpy as np

# Generate an array with values from 12 to 38 (inclusive)
array = np.arange(12, 39)

print("Array with values from 12 to 38:")
print(array)


Array with values from 12 to 38:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [3]:
import numpy as np

# Define the list and tuple
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
my_tuple = ([8, 4, 6], [1, 2, 3])

# Convert the list and tuple into NumPy arrays
array_from_list = np.array(my_list)
array_from_tuple = np.array(my_tuple)

print("Array from list:")
print(array_from_list)

print("\nArray from tuple:")
print(array_from_tuple)


Array from list:
[1 2 3 4 5 6 7 8]

Array from tuple:
[[8 4 6]
 [1 2 3]]
